name: Minify HTML

on:
  push:
    branches: [ main ]
    # Sadece bu dosyalar değiştiğinde tetiklenmesi için (istersen genişletebilirsin)
    paths:
      - 'index.html'
      - 'assets/**/*.css'
      - 'assets/**/*.js'

permissions:
  contents: write

jobs:
  minify:
    # Workflow'un kendi "chore: minify" commit'inde tekrar çalışıp döngüye girmesin
    if: "!contains(github.event.head_commit.message, 'chore: minify')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Gerekli minify araçlarını kur
      - run: npm i -g html-minifier-terser clean-css-cli uglify-js

      # HTML (inline CSS/JS dâhil) minify
      - run: |
          html-minifier-terser index.html -o index.html \
            --collapse-whitespace --remove-comments --minify-css true --minify-js true

      # (Opsiyonel) Ayrı CSS/JS dosyaların varsa, şu örnekleri de ekleyebilirsin:
      # - run: cleancss -o assets/css/styles.min.css assets/css/styles.css
      # - run: uglifyjs assets/js/app.js -o assets/js/app.min.js -c -m

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "chore: minify" || echo "No changes"
          git push
